# Generated by Django 5.2.4 on 2025-07-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0002_remove_post_author_id_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
